name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: test
    - run: cargo test
    - name: Build
      run: cargo build --release
    - name: make dir
      run: mkdir app
    - name: copy
      run: mv ./target/release/axum-deom ./app/axum
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "axum-demo-try2"
        heroku_email: "anshulgoel151999@gmail.com"
        appdir: "./app"
        procfile: "web: ./axum"
        buildpack: "https://github.com/ph3nx/heroku-binary-buildpack.git"
  
